/**
 * User: Himal_J
 * Date: 3/5/2025
 * Time: 12:55 PM
 * <p>
 */

package com.dtech.claim.enums;

public enum CommonParam {
    INSURANCE_CLAIM_REQUEST_PERIOD,
    DEATH_CLAIM_REQUEST_PERIOD,
    DEATH_CLAIM_REQUEST_HALF_PAYMENT_PERIOD,
    DEATH_AGE,
    TREATMENT_BILL_MAX_IMAGE,
    DIAGNOSIS_CARD_MAX_IMAGE,
    DEATH_CERTIFICATE_MAX_IMAGE,
    EMPLOYEE_MAX_AGE_FOR_REQUEST_DDF,
    DDF_REQUEST_CHILDREN_MIN_AGE,
    DDF_REQUEST_PER_MIN_PERIOD,
}
