#Signup
val.employee.details.not.found = Your details are not registered in the system Please contact {0} for assistance
val.employee.already.signup = You are already registered Please sign in
val.employee.details.inquiry.success = Employee details inquiry was successful
val.application.user.password.policy.not.found = Password policy is unavailable
val.otp.send.success = OTP sent successfully
val.otp.already.verified = OTP has already been verified
val.otp.send.failed = Failed to send OTP Please try again
val.application.otp.not.found = OTP session unavailable
val.application.onboarding.verification.otp.not.found = Onboarding OTP verification is unavailable
val.application.otp.invalid.or.session.timeout = OTP is invalid or the session has timed out
val.application.otp.validation.success = OTP verification successful
val.application.username.already.exists = The username already exists Please try another one
val.password.max.length.invalid = Password exceeds the maximum length The required length is {0}
val.password.min.length.invalid = Password does not meet the minimum length The required length is {0}
val.password.upper.length.invalid = Password must contain at least {0} uppercase letter(s)
val.password.lower.length.invalid = Password must contain at least {0} lowercase letter(s)
val.password.number.length.invalid = Password must contain at least {0} number(s)
val.password.special.length.invalid = Password must contain at least {0} special character(s)
val.password.policy.notfound = Password policy is unavailable
val.application.signup.process.success = Congratulations You have successfully completed the onboarding process
val.username.max.length.invalid = Username exceeds the maximum length The required length is {0}
val.username.min.length.invalid = Username does not meet the minimum length The required length is {0}
val.username.upper.length.invalid = Username must contain at least {0} uppercase letter(s)
val.username.lower.length.invalid = Username must contain at least {0} lowercase letter(s)
val.username.number.length.invalid = Username must contain at least {0} number(s)
val.username.special.length.invalid = Username must contain at least {0} special character(s)
val.username.policy.notfound = Username policy is unavailable
val.company.types.notfound = Company types are unavailable
val.staff.category.notfound = Staff category is unavailable
val.staff.type.notfound = Staff type is unavailable
val.application.user.not.found = User not found
val.application.profile.success = User profile details retrieved successfully
val.claim.dependent.mother.found = Sorry, mother not found Please contact your {0} for assistance
val.claim.dependent.father.found = Sorry, father not found Please contact your {0} for assistance
val.claim.dependent.added.success = Dependent(s) added successfully
val.claim.dependent.wife.document.is.empty.or.out.of.range = Wife's documents are out of range {0}
val.claim.dependent.other.relation.category.document.is.empty.or.out.of.range = Documents for parents or children are out of range {0}
val.claim.dependent.list.view.success = Claim dependent details inquiry was successful
val.primary.mobile.already.in.use = This mobile number is already in used
val.primary.email.already.in.use = This email address is already in used
val.profile.image.update.success = Profile image updated successfully
val.application.user.otp.session.not.found = OTP session unavailable
val.application.user.otp.session.60s = Please try again after 60 seconds
val.application.user.otp.send.success = OTP sent successfully
val.application.user.otp.exceed = OTP attempt limit exceeded Please try again later or contact support after {0} minutes
val.application.user.details.not.change = Profile details could not be updated
val.application.user.details.update.success = Profile details updated successfully
val.application.user.otp.verification.failed = OTP verification failed Unable to update profile details
val.notification.template.not.found = Notification template is unavailable
val.notification.filter.list.success = Notification request history filter list retrieved successfully
val.notification.history.not.found = Notification session unavailable
val.notification.history.read.state.update.success = Notification read state update successfully
